name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev

    - name: Install additional build dependencies
      run: |
        sudo apt-get install -y \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good
        sudo apt-get install -y libffi-dev
        sudo apt-get install -y autoconf automake
        sudo apt-get install -y libltdl-dev
        sudo apt-get install -y pkg-config

    - name: Accept Android SDK licenses
      run: yes | buildozer android update 2>&1 | grep -v "no version information"

    - name: Build with Buildozer
      run: |
        # Build the APK
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: pytorn-debug
        path: bin/*.apk
