name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Use v4

    - name: Set up Python
      uses: actions/setup-python@v5 # Use v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install Cython first if jnius is needed for Windows build
        # Consider removing jnius/buildozer from requirements.txt if not needed for Windows
        pip install Cython
        pip install -r requirements.txt
        pip install pyinstaller
      # Add error handling if needed: shell: pwsh {0} -ErrorAction Stop

    - name: Build executable
      run: |
        # Build the executable with PyInstaller
        pyinstaller --onefile --windowed --name PyTorn app/main.py
      # Add error handling if needed: shell: pwsh {0} -ErrorAction Stop

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: pytorn-windows-exe # Artifact name on GitHub (will download as .zip)
        path: dist/PyTorn.exe    # Path to the actual executable to be zipped
        if-no-files-found: error # Fail the workflow if the exe wasn't created
